server:
  port: 8090

# FOR CONFIG SERVER
spring:
  application:
    # SAME NAME AS THE PROFILE PROPERTIES FILE
    # IN THE CONFIG SERVER
    name: "loans"

  # ACTIVATE DEFAULT PROFILE
  profiles:
    active: "prod"

  datasource:
    url: jdbc:mysql://localhost:3309/loansdb
    username: root
    password: Galerien3?

  sql:
    init:
      mode: always

  jpa:
    show-sql: true

  # CONFIG SERVER CONNECT
  config:
    import: "optional:configserver:http://localhost:8071/"

  # ENABLE COLOR ON TERMINAL ENTRIES
  output:
    ansi:
      enabled: ALWAYS

# ENABLING ACTUATORS PATH LIKE REFRESH PATH
# TO READ CHANGED PROPERTIES AT RUNTIME
# WITHOUT RESTARTING THE ÂµSERVICES
management:
  endpoints:
    web:
      exposure:
        include: "*"